# Create Departments
owner_department = Department.find_or_create_by!(name: 'Franchise Owner')
admin_department = Department.find_or_create_by!(name: 'Administration')
sales_department = Department.find_or_create_by!(name: 'Sales')
marketing_department = Department.find_or_create_by!(name: 'Marketing')
finance_department = Department.find_or_create_by!(name: 'Finance')
order_management_department = Department.find_or_create_by!(name: 'Order Management')

# Create Roles
super_role = Role.find_or_create_by(name: 'SuperAdministrator')
admin_manager_role = Role.find_or_create_by!(name: 'AdminManager')
admin_staff_role = Role.find_or_create_by!(name: 'AdminStaff')
sales_manager_role = Role.find_or_create_by!(name: 'SalesManager')
sales_associate_role = Role.find_or_create_by!(name: 'SalesAssociate')
marketing_manager_role = Role.find_or_create_by!(name: 'MarketingManager')
marketing_staff_role = Role.find_or_create_by!(name: 'MarketingStaff')
finance_manager_role = Role.find_or_create_by!(name: 'FinanceManager')
finance_staff_role = Role.find_or_create_by!(name: 'FinanceStaff')
order_manager_role = Role.find_or_create_by!(name: 'OrderManager')
order_processor_role = Role.find_or_create_by!(name: 'OrderProcessor')

# Assign Roles to Departments
DepartmentRole.find_or_create_by!(department: admin_department, role: admin_manager_role)
DepartmentRole.find_or_create_by!(department: admin_department, role: admin_staff_role)
DepartmentRole.find_or_create_by!(department: sales_department, role: sales_manager_role)
DepartmentRole.find_or_create_by!(department: sales_department, role: sales_associate_role)
DepartmentRole.find_or_create_by!(department: marketing_department, role: marketing_manager_role)
DepartmentRole.find_or_create_by!(department: marketing_department, role: marketing_staff_role)
DepartmentRole.find_or_create_by!(department: finance_department, role: finance_manager_role)
DepartmentRole.find_or_create_by!(department: finance_department, role: finance_staff_role)
DepartmentRole.find_or_create_by!(department: order_management_department, role: order_manager_role)
DepartmentRole.find_or_create_by!(department: order_management_department, role: order_processor_role)
DepartmentRole.find_or_create_by!(department: owner_department, role: super_role)
