inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - vendor/**/* # or vendor/bundle/**/*

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/environments/*.rb
    - config/routes/**/*
    - config/routes.rb
    - app/admin/*.rb

Style/ClassAndModuleChildren:
  Enabled: false
