# frozen_string_literal: true

# Whodunit configuration
# This file was generated by `whodunit install` command.
# Uncomment and modify the options you want to customize.

if defined?(Rails::Server)
  Whodunit.configure do |config|
    # User model configuration
    # Specify which model represents users in your application
    config.user_class = 'AdminUser'
    # Use 'Account', 'Admin', etc. if your user model has a different name

    # Column name configuration
    # Customize the names of the tracking columns in your database
    # config.creator_column = :created_by_id # Default: :creator_id
    # Column that stores who created the record
    # config.updater_column = :updated_by_id # Default: :updater_id
    # Column that stores who last updated the record
    # config.deleter_column = :deleted_by_id # Default: :deleter_id
    # Column that stores who deleted the record (soft-delete only)

    # Soft-delete integration
    # Enable tracking of who deleted records when using soft-delete gems
    # config.soft_delete_column = :discarded_at # Default: nil (disabled)
    # Set to :deleted_at for Paranoia gem
    # Set to :discarded_at for Discard gem
    # Set to your custom soft-delete column name
    # Set to nil to disable soft-delete tracking

    # Migration auto-injection
    # Control whether whodunit stamps are automatically added to new migrations
    # config.auto_inject_whodunit_stamps = false # Default: true
    # When true, automatically adds t.whodunit_stamps to create_table migrations
    # When false, you must manually add t.whodunit_stamps to your migrations

    # Column data type configuration
    # Configure what data types to use for the tracking columns
    # config.column_data_type = :integer # Default: :bigint
    # Global default for all stamp columns
    # Common options: :bigint, :integer, :string, :uuid

    # Individual column type overrides
    # Override the data type for specific columns (takes precedence over column_data_type)
    # config.creator_column_type = :string # Default: nil (uses column_data_type)
    # Useful if your user IDs are strings or UUIDs
    # config.updater_column_type = :uuid # Default: nil (uses column_data_type)
    # Set to match your user model's primary key type
    # config.deleter_column_type = :integer # Default: nil (uses column_data_type)
    # Only used when soft_delete_column is configured
  end
end
