development:
  forest_env_secret: 559a03cce98fcea4347bad96c6873e0e3d04e883ee2d63d5fb1e0aa9102ad6f3
  forest_auth_secret: REDACTED_FOREST_AUTH_SECRET
staging:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
production:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
